application:
  external:
    backends:
      backend-service-2:
        base-url: https://backend-service-2
      external-service-1:
        base-url: https://egress-gateway/es1

spring:
  application:
    name: backend-service-1
