application:
  external:
    backends:
      inventory-service:
        base-url: https://backend-service-2
      payment-service:
        base-url: https://egress-gateway/es1

spring:
  application:
    name: order-service
